<?php


namespace app\admin\controller;


use think\Controller;
use think\Db;

class Category extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }

    public function add(){
        //权限
        if (!$this->request->isPost()){
            return json([
                'code'=>404,
                'msg'=>'请求方式错误'
            ]);
        }
        $data = $this->request->post();
        $validate = validate('Category');
        if (!$validate->scene('add')->check($data)){
            return json([
               'code'=>404,
                'msg'=>$validate->getError()
            ]);
        }
        $result=Db::table('category')->field('cname,cdesc')->insert($data);
        if ($result){
            return json([
                'code'=>200,
                'msg'=>'分类添加成功'
            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'分类添加失败'
            ]);
        }
    }

    public function index(){
        $data = $this->request->get();
        if(isset($data['page']) && !empty($data['page'])){
            $page = $data['page'];
        }else{
            $page = 1;
        }
        if(isset($data['limit']) && !empty($data['limit'])){
            $limit = $data['limit'];
        }else{
            $limit = 5;
        }
        $where = [];
        if (isset($data['cname']) && !empty($data['cname'])){
            $where['cname'] = ['like','%'.$data['cname'].'%'];
        }
        $category = Db::table('category')->field('cid,cname,cdesc')->where($where)->page($page)->limit($limit)->select();
        $count = Db::table('category')->where($where)->count();

        if ($category && $count){
            return json([
               'code'=>200,
               'msg'=>'数据获取成功',
                'data'=>$category,
                'total'=>$count
            ]);
        }else{
            return json([
                'code'=>200,
                'msg'=>'暂无数据'
            ]);
        }
    }

    public function indexall(){
        $category = Db::table('category')->field('cid,cname,cdesc')->select();
        if ($category){
            return json([
                'code'=>200,
                'msg'=>'数据获取成功',
                'data'=>$category,
            ]);
        }else{
            return json([
                'code'=>200,
                'msg'=>'暂无数据'
            ]);
        }
    }

    public function read(){
        $data = $this->request->get();
        $validate=validate('Category');
        if (!($validate->scene('read')->check($data))){
            return json([
                'code'=>404,
                'msg'=>$validate->getError()
            ]);
        }
        $category=Db::table('category')->where('cid',$data['cid'])->find();
        if ($category){
            return json([
                'code'=>200,
                'msg'=>'数据获取成功',
                'data'=>$category
            ]);
        }else{
            return json([
                'code'=>200,
                'msg'=>'暂无数据'
            ]);
        }
    }

    public function edit(){
        if (!$this->request->isPost()){
            return json([
                'code'=>404,
                'msg'=>'请求方式错误'
            ]);
        }
        $data = $this->request->post();
        $validate = validate('Category');
        if (!$validate->scene('add')->check($data)){
            return json([
                'code'=>404,
                'msg'=>$validate->getError()
            ]);
        }
        $result=Db::table('category')->where('cid',$data['cid'])->update(['cname'=>$data['cname'],'cdesc'=>$data['cdesc']]);
        if ($result){
            return json([
                'code'=>200,
                'msg'=>'分类修改成功'
            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'分类修改失败'
            ]);
        }
    }

    public function delete(){
        $data = $this->request->post();
        $validate=validate('Category');
        if (!($validate->scene('read')->check($data))){
            return json([
                'code'=>404,
                'msg'=>$validate->getError()
            ]);
        }
        $result=Db::table('category')->where('cid',$data['cid'])->delete();
        if ($result){
            return json([
                'code'=>200,
                'msg'=>'分类删除成功'
            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>'分类删除失败'
            ]);
        }
    }


}